import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import { useSession } from "next-auth/react";
import Router from "next/router";

export default function Home() {
  const { data: session, loading } = useSession();

  if (!session) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Drag And Drop</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Link href="http://localhost:3000/api/auth/signin">
            <button>Login with Github</button>
          </Link>
        </main>
      </div>
    );
  } else {
    Router.push(`/drop/${session.user.name}`);
  }
}
