import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Dropzone from "./Dropzone";

export default function Drop() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drag And Drop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Dropzone />
      </main>
    </div>
  );
}
