import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Error() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drag And Drop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image src="/../public/error_icon.png" width={200} height={200}></Image>
        <h1>Access Denied</h1>
        <div className={styles.goingback}>
          <Image src="/../public/left_arrow.png" width={20} height={20}></Image>
          <Link href="/">
            <a className={styles.back_link}>Go back to login page</a>
          </Link>
        </div>
      </main>
    </div>
  );
}
