import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import LogInFrame from "../components/LogInFrame";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drag And Drop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LogInFrame />
      </main>
    </div>
  );
}
